### ISSUE TITLE
[Running big set]: Error again with loading gene mentions into db...

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#122]
Going to try running again, but error is:

``` bash
08:08:33 [taskManager] INFO  Memory usage: 294/1627MB (max: 233017MB)
08:08:59 [extractorRunner-gene_extract_candidates] ERROR Failure when executing script: /tmp/gene_me
ntions.copy1099686395117919219.sh
java.lang.RuntimeException: Failure when executing script: /tmp/gene_mentions.copy109968639511791921
9.sh
        at org.deepdive.helpers.Helpers$.executeCmd(Helpers.scala:102) ~[classes/:na]
        at org.deepdive.datastore.DataLoader.load(Dataloader.scala:170) ~[classes/:na]
        at org.deepdive.extraction.ExtractorRunner.org$deepdive$extraction$ExtractorRunner$$runTsvEx
tractor(ExtractorRunner.scala:496) ~[classes/:na]
        at org.deepdive.extraction.ExtractorRunner$$anonfun$2.applyOrElse(ExtractorRunner.scala:131)
 ~[classes/:na]
        at org.deepdive.extraction.ExtractorRunner$$anonfun$2.applyOrElse(ExtractorRunner.scala:100)
 ~[classes/:na]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) ~[scala-lib
rary.jar:0.13.1]
        at akka.actor.FSM$class.processEvent(FSM.scala:587) ~[akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at org.deepdive.extraction.ExtractorRunner.processEvent(ExtractorRunner.scala:59) ~[classes/
:na]
        at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:581) ~[akka-actor_2.10-2.3-M2.j
ar:2.3-M2]
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:575) ~[akka-actor_2.10-2.3-M2.jar
:2.3-M2]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.10-2.3-M2.jar:2.3-M2
]
        at org.deepdive.extraction.ExtractorRunner.aroundReceive(ExtractorRunner.scala:59) ~[classes
/:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:491) [akka-actor_2.10-2.3-M2.jar:2.3-
M2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:462) [akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237) [akka-actor_2.10-2.3-M2.jar:2.3-M
2]
        at akka.dispatch.Mailbox.run(Mailbox.scala:219) [akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala
:385) [akka-actor_2.10-2.3-M2.jar:2.3-M2]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:n
a]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-l
ibrary.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.j
ar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-
library.jar:na]
08:08:59 [extractorRunner-gene_extract_candidates] INFO  waiting for tasks
08:08:59 [extractorRunner-gene_extract_candidates] WARN  unhandled event PrintStatus in state Idle
```

**Comment by ajratner** [comment]
Ran it again and it worked... can always re-open...
